version: '3.7'

services:
  kszkepzes-backend:
    build: 
      context: ./kszkepzes-backend
      dockerfile: Dockerfile.prod
    command: gunicorn kszkepzes.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/kszkepzes-backend/staticfiles
      - media_volume:/home/app/kszkepzes-backend/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  kszkepzes-frontend:
    build: ./kszkepzes-frontend
    command: npm start
    expose:
      - 3000
    depends_on:
      - kszkepzes-backend
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/kszkepzes-backend/staticfiles
      - media_volume:/home/app/kszkepzes-backend/mediafiles
    ports:
      - '127.0.0.1:80:80'
    depends_on:
      - kszkepzes-backend
      - kszkepzes-frontend

volumes:
  postgres_data:
  static_volume:
  media_volume:
