version: '3.7'

services:
  kszkepzes-backend:
    build: ./kszkepzes-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - ./kszkepzes-backend/src/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=kszkepzes
  kszkepzes-frontend:
    build: ./kszkepzes-frontend
    command: npm start
    volumes:
    - ./kszkepzes-frontend/:/usr/app/
    ports:
      - 3000:3000
    depends_on:
      - kszkepzes-backend

volumes:
  postgres_data:
